name: Cypress

on: pull_request

concurrency:
  group: cypress-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  # Adjust APP_NAME if your repository name is different
  APP_NAME: ${{ github.event.repository.name }}
  CYPRESS_baseUrl: http://localhost:8081/index.php

jobs:
  cypress:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.0']
        databases: ['sqlite']
        server-versions: ['stable25', 'master']
        include:
          - php-versions: '7.3'
            server-versions: 'stable22'
          - php-versions: '7.4'
            server-versions: 'stable23'

    steps:
      - name: Set app env
        run: |
          # Split and keep last
          echo "APP_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@e6f75134d35752277f093989e72e140eaa222f35 # v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, iconv, fileinfo, intl, sqlite, pdo_sqlite, gd
          coverage: none

      - name: Checkout server
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          submodules: true
          repository: nextcloud/server
          ref: ${{ matrix.server-versions }}

      - name: Checkout app
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          path: apps/${{ env.APP_NAME }}

      - name: Read package.json node and npm engines version
        uses: skjnldsv/read-package-engines-version-actions@8205673bab74a63eb9b8093402fd9e0e018663a1 # v2.2
        id: versions
        with:
          path: apps/${{ env.APP_NAME }}
          fallbackNode: "^20"
          fallbackNpm: "^10"

      - name: Set up node ${{ steps.versions.outputs.nodeVersion }}
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: ${{ steps.versions.outputs.nodeVersion }}

      - name: Set up npm ${{ steps.versions.outputs.npmVersion }}
        run: npm i -g npm@"${{ steps.versions.outputs.npmVersion }}"

      - name: Setup NPM cache
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          cache: 'npm'
          cache-dependency-path: apps/${{ env.APP_NAME }}/package-lock.json
          # cypress will install dependencies

      - name: Install dependencies & build
        working-directory: apps/${{ env.APP_NAME }}
        run: |
          npm ci
          npm run build --if-present

      - name: Set up Nextcloud
        env:
          DB_PORT: 4444
        run: |
          mkdir data
          ./occ maintenance:install --verbose --database=sqlite --database-name=nextcloud --database-host=127.0.0.1 --database-port=$DB_PORT --database-user=root --database-pass=rootpassword --admin-user admin --admin-pass admin
          ./occ app:enable --force ${{ env.APP_NAME }}

      - name: Run Nextcloud
        run: php -S 0.0.0.0:8081 &
        env:
          PHP_CLI_SERVER_WORKERS: 3

      - name: Cypress run
        uses: cypress-io/github-action@ebe8b24c4428922d0f793a5c4c96853a633180e3 # v6.6.0
        with:
          record: true
          wait-on: '${{ env.CYPRESS_baseUrl }}'
          working-directory: apps/${{ env.APP_NAME }}
          config: video=false,defaultCommandTimeout=20000
          tag: ${{ github.event_name }}
        env:
          # https://github.com/cypress-io/github-action/issues/124
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
          COMMIT_INFO_SHA: ${{ github.event.pull_request.head.sha }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_ncVersion: ${{ matrix.server-versions }}

      - name: Upload snapshots
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        if: failure()
        with:
          name: snapshots_${{ matrix.server-versions }}
          path: apps/${{ env.APP_NAME }}/cypress/screenshots/

      - name: Upload NC logs
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        if: failure()
        with:
          name: nc_logs_${{ matrix.server-versions }}.log
          path: data/nextcloud.log

  summary:
    runs-on: ubuntu-latest
    needs: cypress

    if: always()

    name: cypress-summary

    steps:
      - name: Summary status
        run: if ${{ needs.cypress.result != 'success' }}; then exit 1; fi
